package utils

var (
	RaccoonFacts = []string{
		"Raccoons have a form of “night vision” and see better in the dark due to adapted eyes.",
		"They can rotate their hind feet 180 degrees, enabling them to climb down trees headfirst.",
		"Raccoons don't just wash their food; they play with it in water to learn more about it.",
		"They can remember task solutions for up to three years, showcasing high intelligence.",
		"Some raccoons in Japan are considered sacred and bring good luck.",
		"Raccoons can lose up to 50% of their body weight during winter, using stored fat to survive.",
		"The “bandit mask” around their eyes reduces glare and enhances night vision.",
		"They can recognize themselves in a mirror, a rare ability among animals.",
		"Raccoons are kept as pets, especially in Japan, due to the popularity of the anime “Rascal the Raccoon.”",
		"Raccoons have sensitive hands with acute touch, especially when wet.",
		"Their teeth can crack a turtle's shell.",
		"They are capable of swimming long distances, several miles at a time.",
		"Over 50 vocal sounds are used for communication.",
		"The Latin name, Procyon Lotor, means “washer dog.”",
		"Raccoons are native to North America but found in Europe and Japan due to human introduction.",
		"Urban raccoons adapt to using human tools like door handles.",
		"Dexterous paws allow them to untie knots, turn doorknobs, and open jars.",
		"Raccoons can make a purring noise similar to cats.",
		"A group of raccoons is called a “nursery” or a “gaze.”",
		"They have an omnivorous diet and can eat a vast range of foods.",
		"Baby raccoons are called “kits.”",
		"The smallest raccoon species weighs only 3.5 lbs.",
		"Raccoons tails have anywhere from 4 to 10 rings, believed to provide balance.",
		"Raccoons can run up to 15 miles per hour.",
		"They use over 75% of their sensory perception for a high sense of touch in their front paws.",
		"In captivity, raccoons can live up to 20 years, while in the wild, they usually live 2 to 3 years.",
		"They are good climbers and can drop from heights of up to 40 feet without injury.",
		"Despite their small size, raccoons can become quite aggressive when threatened.",
		"In colder climates, raccoons have been known to sleep in communal dens for warmth.",
		"Raccoons are one of the few mammals that can descend a tree headfirst.",
		"They are not very social but will communicate with each other using over 200 different sounds and 12-15 different calls.",
		"The word “raccoon” is derived from the Powhatan word “aroughcun,” meaning “animal that scratches with its hands.”",
		"Raccoons do not have opposable thumbs, but they can still grasp objects.",
		"Raccoons have been seen rolling rocks and stones, just for fun.",
		"They can adapt to a wide range of habitats, from forests to cities.",
		"Raccoons can cause power outages by tampering with power supply equipment.",
		"They have a keen sense of hearing that can pick up on even the smallest of sounds.",
		"Raccoons are often seen “washing” their food, rubbing and dunking it in water before eating, not for cleanliness but to learn about it.",
		"The fur of the raccoon was once used to make coats and hats, contributing to the decline of their populations in the 19th and 20th centuries.",
		"Raccoons have been found living in attics, chimneys, sheds, and even in parked cars.",
		"They have a home range of about 1 mile in urban areas and up to 20 miles in rural settings.",
		"Raccoons can weigh up to 60 pounds in the wild, but the largest recorded raccoon weighed a staggering 75 pounds.",
		"Their mating season typically occurs in late winter to early spring.",
		"A mother raccoon is very protective of her kits and will relocate them to different dens regularly to avoid predators.",
		"They have been known to break into homes to access food or to find a cozy place to sleep.",
		"Despite their cute appearance, raccoons are known carriers of several diseases, including rabies.",
		"They are mostly nocturnal but can be active during the day if they're hungry or have babies to feed.",
		"Raccoons sometimes play dead when they feel threatened to trick their predators.",
		"The fur color of a raccoon can range from gray to brown, and some can even appear to be reddish.",
		"Raccoons have been observed engaging in play behaviors, such as wrestling and sliding down slopes.",
		"Although raccoons appear chubby, their fur makes them look larger than they actually are.",
		"They are excellent swimmers and do not hesitate to jump into water bodies to escape from predators.",
		"Raccoons are excellent foragers. They can forage for food in the dark, using their sensitive hands.",
		"A raccoons tracks look like small human handprints and footprints.",
		"They are known to travel up to 18 miles in search of food.",
		"Raccoons communicate with each other using a variety of sounds, body postures, and signals.",
		"They have a peculiar habit of dipping food in water before eating it, but this doesn't mean they're trying to wash it.",
		"Some raccoons have adapted to urban environments so well they can open doors and refrigerators.",
		"Raccoons forepaws are similar to human hands, but they lack the thumb dexterity that humans possess.",
		"They are known to be quite noisy, particularly when they feel threatened or are looking for a mate.",
		"Raccoons are not great travelers, and they usually stay within 1 mile of their homes.",
		"The raccoon is a symbol of curiosity, adaptability, and resourcefulness in many cultures.",
		"In the wild, raccoons often dip their food in water, possibly to remove unwanted parts or simply because they like the feel of water on their hands.",
		"The English name raccoon was adopted by Captain John Smith, of Jamestown, Virginia, from a term used by the native Powhatan, in the early 17th century.",
		"Raccoons have whiskers on their toes to help them identify objects before they touch them.",
		"In some regions, raccoons are seen as pests because they can carry diseases and often rifle through garbage.",
		"Raccoons have five toes on each foot and have a stride of about 12 inches.",
		"The size of a raccoons home range will depend on the age, sex, and social status of the raccoon.",
		"Raccoons have an incredibly varied diet, and they've been known to eat insects, birds, fruit, and even wall insulation!",
		"They can carry a parasite called Baylisascaris procyonis, which can be dangerous or even deadly to humans and pets.",
		"The American Black Bear is one of the few predators raccoons need to worry about.",
		"A raccoons sense of touch is its most important when it comes to hunting, especially since most of its hunting is done at night.",
		"Their black and gray fur provides an excellent camouflage during nighttime foraging.",
		"Raccoons are excellent climbers and are capable of reaching bird nests or rooftop nesting areas quite easily.",
		"In winter, raccoons don't hibernate, but they do stay in their dens and sleep most of the time.",
		"Despite being solitary animals, raccoons sometimes form gender-specific groups or “families” to better protect themselves.",
		"The most common predators of the raccoon are bobcats, coyotes, and owls.",
		"The oldest known raccoon lived to be 21 years old.",
		"Raccoons are most active in the spring and summer months.",
		"Some raccoons have been observed using stones and other objects as tools.",
		"Raccoons use their tails for balance when climbing.",
		"When a raccoon is excited, it may exhibit a strange hopping behavior.",
		"In cities, raccoons are known to pick locks, open latches, and rummage through trash cans for food.",
		"Raccoons are excellent problem solvers and are known to remember solutions to tasks for up to three years.",
		"Female raccoons typically give birth to two to five kits in early summer.",
		"Raccoons dense underfur insulates them against cold weather.",
		"They are found across North America, from Canada to Panama.",
		"Raccoons often follow a precise path day after day, leading them to a reliable food source.",
		"They can contract and carry a number of diseases, including canine distemper, leptospirosis, and parasitic infections.",
		"Raccoons can lose a lot of their body heat through their feet, just like dogs.",
		"Raccoons typically do not make long migrations, but they will move to lower elevations during the winter to stay warm.",
		"Raccoons have a biting force of 32 pounds per square inch, which is only slightly less than a dogs bite force.",
		"They tend to favor deciduous and mixed forests but can adapt to various environments, including urban and suburban areas.",
		"Male raccoons, especially youngsters, have the tendency to be more nomadic than females.",
		"In the wild, raccoons live in hollow trees, ground burrows, brush piles, muskrat houses, barns, and attics.",
		"Raccoons are often hunted for their fur. Each year, around 400,000 to a million raccoons are hunted or trapped.",
		"Unlike dogs and cats, raccoons do not drool. Their mouths stay dry even when they are panting from heat or exhaustion.",
		"Some raccoons use a special whistle sound to call their young ones. This whistle is different for each raccoon family.",
		"Raccoons are known for their dexterous front paws, allowing them to manipulate objects with precision.",
		"They have a remarkable ability to adapt to various environmental conditions, showcasing their versatility.",
		"Raccoons are opportunistic feeders, and their diet can include fruits, vegetables, small mammals, and even bird eggs.",
		"Despite their agility in climbing, raccoons are also skilled swimmers and can navigate through water bodies with ease.",
		"Raccoons communicate using body language, and their tail movements and postures convey information to other raccoons.",
		"During the mating season, male raccoons may travel long distances in search of a mate, displaying their nomadic behavior.",
		"The mating season typically results in multiple males competing for the attention of a female raccoon.",
		"Raccoons have a complex social structure, and their interactions involve a combination of vocalizations and physical gestures.",
		"Raccoons exhibit a curious nature, exploring their surroundings and investigating new objects they encounter.",
		"They have an exceptional memory, which aids in remembering the locations of food sources and potential shelter spots.",
		"Raccoons have a strong maternal instinct, and mother raccoons invest significant time and effort in raising their offspring.",
		"In the wild, raccoons construct dens in various locations, such as tree hollows, rock crevices, and abandoned burrows.",
		"The raccoon's scientific classification places it in the family Procyonidae, along with coatis and kinkajous.",
		"Raccoons are known to engage in play activities, such as chasing, wrestling, and even sliding down inclined surfaces.",
		"Their keen sense of smell contributes to their foraging abilities, allowing them to locate food even in challenging conditions.",
		"Raccoons may create communal latrines, known as raccoon latrines, where multiple individuals deposit their feces.",
		"The intricate patterns on a raccoon's tail serve as a distinctive feature, aiding in identification within the species.",
		"Raccoons are crepuscular, meaning they are most active during dawn and dusk, aligning with their nocturnal tendencies.",
		"In addition to their natural behaviors, raccoons are often featured in folklore and stories across various cultures.",
		"Raccoons possess a high level of adaptability to urban environments, leading to their presence in cities worldwide.",
		"Their front paw structure, with five toes resembling fingers, contributes to their ability to grasp and manipulate objects.",
		"Raccoons exhibit curiosity not only in their immediate surroundings but also in novel items introduced into their environment.",
		"Despite being considered pests in some areas, raccoons play a crucial role in controlling insect and rodent populations.",
		"Raccoons can live in close proximity to humans, utilizing human-made structures for shelter and nesting.",
	}
)
